run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    # don't enable:
    # - asciicheck
    # - scopelint
    # - gochecknoinits
    # - gochecknoglobals
    # - gocognit
    # - godot
    # - godox
    # - goerr113
    # - gomnd
    # - interfacer
    # - lll
    # - maligned
    # - nestif
    # - prealloc
    # - revive
    # - testpackage
    # - wsl
  fast: false
