builds:
  - binary: milvus-cli
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

universal_binaries:
  - replace: true

checksum:
  name_template: 'checksums.txt'

dockers:
  - image_templates:
      - "dnat4/milvus-cli:{{ .Tag }}"
      - "dnat4/milvus-cli:v{{ .Major }}"
      - "dnat4/milvus-cli:v{{ .Major }}.{{ .Minor }}"
      - "dnat4/milvus-cli:latest"

report_sizes: true
